name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Get app version
        id: version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          echo "version=$TAG_NAME"
          echo "version=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1

      - name: Build release
        run: cargo build --release --target wasm32-wasip1 --locked

      - name: Generate SHA256 checksum
        run: |
          sha256sum ./target/wasm32-wasip1/release/zellij_ime_per_pane.wasm > \
            ./target/wasm32-wasip1/release/zellij_ime_per_pane.wasm.sha256

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/wasm32-wasip1/release/zellij_ime_per_pane.wasm
            ./target/wasm32-wasip1/release/zellij_ime_per_pane.wasm.sha256
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
